#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-poyo
Version  : 0.5.0
Release  : 17
URL      : https://files.pythonhosted.org/packages/7d/56/01b496f36bbd496aed9351dd1b06cf57fd2f5028480a87adbcf7a4ff1f65/poyo-0.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/7d/56/01b496f36bbd496aed9351dd1b06cf57fd2f5028480a87adbcf7a4ff1f65/poyo-0.5.0.tar.gz
Summary  : A lightweight YAML Parser for Python. 🐓
Group    : Development/Tools
License  : MIT
Requires: pypi-poyo-license = %{version}-%{release}
Requires: pypi-poyo-python = %{version}-%{release}
Requires: pypi-poyo-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
A lightweight YAML Parser for Python. 🐓
        
        **poyo** does not allow deserialization of arbitrary Python objects. Supported
        types are `str`, `bool`, `int`, `float`, `NoneType` as well as `dict` and
        `list` values.
        
        ⚠️ Please note that poyo supports only a chosen subset of the YAML format
        that is required to parse [cookiecutter user configuration
        files][cookiecutterrc]. poyo does not have support for serializing into YAML
        and is not compatible with JSON.

%package license
Summary: license components for the pypi-poyo package.
Group: Default

%description license
license components for the pypi-poyo package.


%package python
Summary: python components for the pypi-poyo package.
Group: Default
Requires: pypi-poyo-python3 = %{version}-%{release}

%description python
python components for the pypi-poyo package.


%package python3
Summary: python3 components for the pypi-poyo package.
Group: Default
Requires: python3-core
Provides: pypi(poyo)

%description python3
python3 components for the pypi-poyo package.


%prep
%setup -q -n poyo-0.5.0
cd %{_builddir}/poyo-0.5.0
pushd ..
cp -a poyo-0.5.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656395353
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-poyo
cp %{_builddir}/poyo-0.5.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-poyo/41557e04db2db0c86215609885cdc73ab769b848
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-poyo/41557e04db2db0c86215609885cdc73ab769b848

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
